variable "access_points" {
  type = map(object({
    posix_user_gid    = optional(number)
    posix_user_uid    = optional(number)
    owner_gid         = optional(number)
    owner_uid         = optional(number)
    owner_permissions = optional(number)
    access_path       = string
  }))
  description = "Map of objects for creation of efs access points"
  default     = {}

  validation {
    condition     = alltrue([for v in var.access_points : lookup(v, "owner_permissions", null) != 777 ? true : false])
    error_message = "Owner permissions cannot be 777 for security reasons."
  }
}

variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. "
  type        = string
  default     = null
}

variable "kms_key_arn" {
  description = "KMS key encryption for EFS data storage"
  type        = string
  default     = null
}

variable "name_prefix" {
  description = "Name prefix for create resources"
  type        = string
}

variable "performance_mode" {
  description = "maxIO"
  type        = string
  default     = "generalPurpose"
}

variable "provisioned_throughput_in_mibps" {
  description = "Provisioned throughput in mibps(1-1024)"
  type        = number
  default     = 0
}

variable "subnet_ids" {
  description = "The created EFS will be available in these subnet ids"
  type        = list(string)
}

variable "transition_to_ia" {
  description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, or AFTER_90_DAYS."
  type        = string
  default     = null
}

variable "tags" {
  description = "A map of tags to add to the resources"
  type        = map(string)
  default     = {}
}

variable "throughput_mode" {
  description = "EFS Throughput mode"
  type        = string
  default     = "bursting"
}

variable "security_groups" {
  description = "Addition security groups for EFS mount points"
  type        = list(string)
}

# EFS Replica Variables

variable "replica_destination" {
  type = object({
    Region   = string
    AZSuffix = optional(string)
    KmsKeyId = string
  })
  description = "EFS replica destination Region, AZ, KMSId"
  default     = null
}

variable "replica_access_points" {
  type = map(object({
    posix_user_gid    = optional(number)
    posix_user_uid    = optional(number)
    owner_gid         = optional(number)
    owner_uid         = optional(number)
    owner_permissions = optional(number)
    access_path       = string
  }))
  description = "Map of objects for creation of the EFS replica access points"
  default     = {}

  validation {
    condition     = alltrue([for v in var.replica_access_points : lookup(v, "owner_permissions", null) != 777 ? true : false])
    error_message = "Owner permissions cannot be 777 for security reasons."
  }
}

variable "replica_subnet_ids" {
  description = "The subnet ids for the replica EFS destination mount target"
  type        = list(string)
  default     = []
}

variable "replica_security_groups" {
  description = "The security groups for replica EFS mount mount target"
  type        = list(string)
  default     = []
}
