---
repos:
  - id: github.com/soansgla/sample-cicd-app
    branch: /.*/
    apply_requirements: [approved, mergeable, undiverged]
    allowed_overrides: [workflow]
    allowed_workflows: [default]
    delete_source_branch_on_merge: true
    pre_workflow_hooks:
      - run: rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
      - run: mkdir -p /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
    post_workflow_hooks:
      - run: |
          infracost comment gitlab \
            --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \
              --merge-request $PULL_NUM \
              --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \
              --gitlab-token $ATLANTIS_GITLAB_TOKEN \
              --behavior new
workflows:
  default:
    plan: {steps: [{run: /home/atlantis/tf_plan.sh}]}
    apply: {steps: [{run: /home/atlantis/apply.sh}]}

